#!/usr/bin/env bash

set -euo pipefail

# VPS (headless server) setup script
# Sets up a dev environment on an Arch Linux VPS with dotfiles, Claude Code, and CLI tools
# Assumes: pacman + yay available, running as non-root user with sudo access

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$DOTFILES_DIR/setup/common.sh"

ensure_not_root
echo "Dotfiles directory: $DOTFILES_DIR"

# --- Package installation ---

install_packages() {
    local to_install=()
    for pkg in "$@"; do
        if ! pacman -Qi "$pkg" &> /dev/null; then
            to_install+=("$pkg")
        fi
    done
    if [ ${#to_install[@]} -gt 0 ]; then
        echo "Installing: ${to_install[*]}"
        yay -S --needed --noconfirm "${to_install[@]}"
    fi
}

# Ensure yay is available
if ! command -v yay &> /dev/null; then
    echo "Error: yay not found. Install it first (gcp-vm-setup.sh installs it)."
    exit 1
fi

# CLI tools
echo "Installing CLI tools..."
install_packages stow zsh neovim fzf ripgrep fd less direnv starship jq zsh-autosuggestions zsh-syntax-highlighting openai-codex tailscale

# --- Tailscale ---

echo "Configuring Tailscale..."
sudo systemctl enable --now tailscaled.service

if ! tailscale status &> /dev/null; then
    echo "Authenticating Tailscale (sets operator=$USER for sudo-free management)..."
    sudo tailscale up --operator="$USER"
else
    # Already connected — ensure operator is set
    sudo tailscale set --operator="$USER"
fi

# --- Rust + cargo tools ---

install_rust_and_cargo

# --- Claude Code ---

install_claude_code

# --- Environment variables ---

echo "Setting system environment variables..."
set_env_var EDITOR nvim

# --- Shell setup ---

setup_zsh_default_shell
create_zshrc_loader

# Remove legacy ~/.tmux.conf (from sambot's gcp-vm-setup.sh)
if [ -f "$HOME/.tmux.conf" ] && [ ! -L "$HOME/.tmux.conf" ]; then
    echo "Removing legacy ~/.tmux.conf (dotfiles version takes over)..."
    rm -f "$HOME/.tmux.conf"
fi

# --- Ensure tms search directories exist ---
mkdir -p "$HOME/Workspace"
if [ "$DOTFILES_DIR" != "$HOME/dotfiles" ] && [ ! -e "$HOME/dotfiles" ]; then
    ln -s "$DOTFILES_DIR" "$HOME/dotfiles"
fi

# --- Stow dotfiles (VPS mode) ---

run_stow_dotfiles --vps

# --- tmux colors fallback ---
# On desktop, Noctalia generates colors.conf dynamically.
# On VPS, provide a static dark theme fallback for the status bar.

COLORS_CONF="$HOME/.config/tmux/colors.conf"
if [ ! -f "$COLORS_CONF" ] || grep -q "Auto-generated by matugen" "$COLORS_CONF" 2>/dev/null; then
    echo "Creating static tmux colors.conf (dark theme fallback)..."
    cat > "$COLORS_CONF" << 'COLORS'
# Static dark theme fallback for VPS (no Noctalia)
# Material Design 3 inspired — matches desktop defaults
set -gq @thm_bg "#121316"
set -gq @thm_fg "#e2e2e6"
set -gq @thm_primary "#9fcaff"
set -gq @thm_on_primary "#003259"
set -gq @thm_inverse_primary "#145eb8"
set -gq @thm_secondary "#bbc7db"
set -gq @thm_tertiary "#d7bee4"
set -gq @thm_on_tertiary "#3b2948"
set -gq @thm_error "#ffb4ab"
set -gq @thm_surface_low "#18191c"
set -gq @thm_surface "#1e2022"
set -gq @thm_surface_variant "#282a2d"
set -gq @thm_outline "#393c42"
set -gq @thm_text_variant "#c3c6cf"
set -gq @thm_primary_container "#0069ec"
set -gq @thm_surface_variant_raw "#1e2022"

# Custom harmonized colors
set -gq @thm_green "#73daa5"
set -gq @thm_on_green "#003822"
set -gq @thm_yellow "#cbcc57"
set -gq @thm_on_yellow "#323200"
set -gq @thm_orange "#ffb783"
set -gq @thm_on_orange "#4f2500"
set -gq @thm_green_container "#005234"
set -gq @thm_on_green_container "#8ff7c0"

# Fallback status background
set -g status-bg "#121316"
COLORS
fi

# --- Git config ---

configure_git_identity

# --- mise ---

run_mise_install

# --- VPS-specific aliases ---

LOCAL_ZSH="$HOME/.config/zsh/local.zsh"
if [ ! -f "$LOCAL_ZSH" ]; then
    echo "Creating VPS-specific aliases..."
    mkdir -p "$(dirname "$LOCAL_ZSH")"
    cat > "$LOCAL_ZSH" << 'LOCAL'
# VPS overrides
alias ws="cd ~/sambot"
LOCAL
fi

# --- Pi Coding Agent ---

"$DOTFILES_DIR/pi_setup.sh"

# --- Secrets ---

copy_secrets_template

# --- Done ---

echo ""
echo "============================================"
echo "  VPS Dev Environment Setup Complete!"
echo "============================================"
echo ""
echo "Log out and back in (or run 'exec zsh') to pick up the new shell."
echo ""
echo "Tailscale: disable key expiry in the admin console for this machine"
echo "  to keep it reachable as a headless server."
echo ""
echo "To authenticate Claude Code from a different account:"
echo "  1. From your local machine:"
echo "     ssh -L 8000:localhost:8000 sambot"
echo ""
echo "  2. On the VPS (through the forwarded session):"
echo "     claude /login"
echo ""
echo "  3. Copy the URL, open in your local browser, and log in."
echo ""
