#!/usr/bin/env bash

set -euo pipefail

# VPS (headless server) setup script
# Sets up a dev environment on an Arch Linux VPS with dotfiles, Claude Code, and CLI tools
# Assumes: pacman + yay available, running as non-root user with sudo access

if [ "$EUID" -eq 0 ]; then
    echo "Please don't run this script as root"
    exit 1
fi

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
echo "Dotfiles directory: $DOTFILES_DIR"

# --- Package installation ---

install_packages() {
    local to_install=()
    for pkg in "$@"; do
        if ! pacman -Qi "$pkg" &> /dev/null; then
            to_install+=("$pkg")
        fi
    done
    if [ ${#to_install[@]} -gt 0 ]; then
        echo "Installing: ${to_install[*]}"
        yay -S --needed --noconfirm "${to_install[@]}"
    fi
}

# Ensure yay is available
if ! command -v yay &> /dev/null; then
    echo "Error: yay not found. Install it first (gcp-vm-setup.sh installs it)."
    exit 1
fi

# CLI tools
echo "Installing CLI tools..."
install_packages stow zsh neovim fzf ripgrep fd less direnv starship jq zsh-autosuggestions zsh-syntax-highlighting openai-codex tailscale

# --- Tailscale ---

echo "Configuring Tailscale..."
sudo systemctl enable --now tailscaled.service

if ! tailscale status &> /dev/null; then
    echo "Authenticating Tailscale (sets operator=$USER for sudo-free management)..."
    sudo tailscale up --operator="$USER"
else
    # Already connected — ensure operator is set
    sudo tailscale set --operator="$USER"
fi

# --- Rust + cargo tools ---

if ! command -v rustup &> /dev/null; then
    echo "Installing Rust..."
    curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
    source "$HOME/.cargo/env"
fi

if ! command -v tms &> /dev/null; then
    echo "Installing tmux-sessionizer..."
    export PATH="$HOME/.cargo/bin:$PATH"
    cargo install tmux-sessionizer
fi

# --- Claude Code ---

if ! command -v claude &> /dev/null; then
    echo "Installing Claude Code..."
    curl -fsSL https://claude.ai/install.sh | bash
fi

# --- Environment variables ---

echo "Setting system environment variables..."
set_env_var() {
    local key="$1" value="$2"
    if grep -q "^${key}=" /etc/environment 2>/dev/null; then
        sudo sed -i "s|^${key}=.*|${key}=${value}|" /etc/environment
    else
        echo "${key}=${value}" | sudo tee -a /etc/environment > /dev/null
    fi
}
set_env_var EDITOR nvim

# --- Shell setup ---

if [[ "$SHELL" != *"zsh"* ]]; then
    echo "Changing default shell to zsh..."
    command -v zsh | sudo tee -a /etc/shells
    sudo chsh -s /usr/bin/zsh "$USER"
fi

# Generate ~/.zshrc loader if it doesn't exist
if [ ! -f "$HOME/.zshrc" ]; then
    echo "Creating ~/.zshrc loader..."
    cat > "$HOME/.zshrc" << 'ZSHRC'
# Source base configuration (managed by dotfiles)
[[ -f ~/.config/zsh/base.zsh ]] && source ~/.config/zsh/base.zsh

# Machine-specific configuration and installer additions below
# (mise, conda, rustup, etc. can safely append here)
ZSHRC
fi

# Remove legacy ~/.tmux.conf (from sambot's gcp-vm-setup.sh)
if [ -f "$HOME/.tmux.conf" ] && [ ! -L "$HOME/.tmux.conf" ]; then
    echo "Removing legacy ~/.tmux.conf (dotfiles version takes over)..."
    rm -f "$HOME/.tmux.conf"
fi

# --- Stow dotfiles (VPS mode) ---

echo "Stowing dotfiles (VPS mode)..."
chmod +x "$DOTFILES_DIR/stow/stow_dotfiles.sh"
"$DOTFILES_DIR/stow/stow_dotfiles.sh" --vps

# --- tmux colors fallback ---
# On desktop, Noctalia generates colors.conf dynamically.
# On VPS, provide a static dark theme fallback for the status bar.

COLORS_CONF="$HOME/.config/tmux/colors.conf"
if [ ! -f "$COLORS_CONF" ] || grep -q "Auto-generated by matugen" "$COLORS_CONF" 2>/dev/null; then
    echo "Creating static tmux colors.conf (dark theme fallback)..."
    cat > "$COLORS_CONF" << 'COLORS'
# Static dark theme fallback for VPS (no Noctalia)
# Material Design 3 inspired — matches desktop defaults
set -gq @thm_bg "#121316"
set -gq @thm_fg "#e2e2e6"
set -gq @thm_primary "#9fcaff"
set -gq @thm_on_primary "#003259"
set -gq @thm_inverse_primary "#145eb8"
set -gq @thm_secondary "#bbc7db"
set -gq @thm_tertiary "#d7bee4"
set -gq @thm_on_tertiary "#3b2948"
set -gq @thm_error "#ffb4ab"
set -gq @thm_surface_low "#18191c"
set -gq @thm_surface "#1e2022"
set -gq @thm_surface_variant "#282a2d"
set -gq @thm_outline "#393c42"
set -gq @thm_text_variant "#c3c6cf"
set -gq @thm_primary_container "#0069ec"
set -gq @thm_surface_variant_raw "#1e2022"

# Custom harmonized colors
set -gq @thm_green "#73daa5"
set -gq @thm_on_green "#003822"
set -gq @thm_yellow "#cbcc57"
set -gq @thm_on_yellow "#323200"
set -gq @thm_orange "#ffb783"
set -gq @thm_on_orange "#4f2500"
set -gq @thm_green_container "#005234"
set -gq @thm_on_green_container "#8ff7c0"

# Fallback status background
set -g status-bg "#121316"
COLORS
fi

# --- Git config ---

if ! git config --global user.name &> /dev/null || ! git config --global user.email &> /dev/null; then
    echo ""
    echo "Git identity not configured."
    read -rp "Git user name: " git_name
    read -rp "Git email: " git_email
    git config --global user.name "$git_name"
    git config --global user.email "$git_email"
    echo "Git identity set to $git_name <$git_email>"
fi

# --- mise ---

if command -v mise &> /dev/null; then
    echo "Installing mise-managed tools (node LTS, etc.)..."
    mise install
fi

# --- VPS-specific aliases ---

LOCAL_ZSH="$HOME/.config/zsh/local.zsh"
if [ ! -f "$LOCAL_ZSH" ]; then
    echo "Creating VPS-specific aliases..."
    mkdir -p "$(dirname "$LOCAL_ZSH")"
    cat > "$LOCAL_ZSH" << 'LOCAL'
# VPS overrides
alias ws="cd ~/sambot"
LOCAL
fi

# --- Pi Coding Agent ---

# Install skills (web search, browser tools, etc.)
# Uses auto-discovery path (~/.pi/agent/skills/) — pi-skills repo lacks
# the package manifest structure that `pi install` expects.
PI_SKILLS_DIR="$HOME/.pi/agent/skills/pi-skills"
if command -v pi &> /dev/null; then
    if [[ ! -d "$PI_SKILLS_DIR" ]]; then
        echo "Installing Pi coding agent skills..."
        git clone https://github.com/badlogic/pi-skills "$PI_SKILLS_DIR"
    else
        echo "Updating Pi coding agent skills..."
        git -C "$PI_SKILLS_DIR" pull --ff-only
    fi
    # Install npm dependencies for skills that need them
    for dir in "$PI_SKILLS_DIR"/*/; do
        if [[ -f "$dir/package.json" && ! -d "$dir/node_modules" ]]; then
            echo "  npm install in $(basename "$dir")..."
            (cd "$dir" && npm install --silent)
        fi
    done
    # Disable unused skills (keep only brave-search + browser-tools)
    PI_SETTINGS="$HOME/.pi/agent/settings.json"
    if [[ -f "$PI_SETTINGS" ]] && ! grep -q '"skills"' "$PI_SETTINGS"; then
        echo "Disabling unused Pi skills (keeping brave-search, browser-tools)..."
        TMP_SETTINGS=$(mktemp)
        node -e "
            const s = JSON.parse(require('fs').readFileSync('$PI_SETTINGS', 'utf8'));
            s.skills = [
                '-skills/pi-skills/gccli/SKILL.md',
                '-skills/pi-skills/gdcli/SKILL.md',
                '-skills/pi-skills/gmcli/SKILL.md',
                '-skills/pi-skills/transcribe/SKILL.md',
                '-skills/pi-skills/vscode/SKILL.md',
                '-skills/pi-skills/youtube-transcript/SKILL.md'
            ];
            require('fs').writeFileSync('$TMP_SETTINGS', JSON.stringify(s, null, 2) + '\n');
        "
        mv "$TMP_SETTINGS" "$PI_SETTINGS"
    fi
else
    echo "Pi coding agent not found, skipping skills install"
fi

# --- Done ---

echo ""
echo "============================================"
echo "  VPS Dev Environment Setup Complete!"
echo "============================================"
echo ""
echo "Log out and back in (or run 'exec zsh') to pick up the new shell."
echo ""
echo "Tailscale: disable key expiry in the admin console for this machine"
echo "  to keep it reachable as a headless server."
echo ""
echo "To authenticate Claude Code from a different account:"
echo "  1. From your local machine:"
echo "     ssh -L 8000:localhost:8000 sambot"
echo ""
echo "  2. On the VPS (through the forwarded session):"
echo "     claude /login"
echo ""
echo "  3. Copy the URL, open in your local browser, and log in."
echo ""
