return {
    base00 = "{{colors.surface.default.hex}}",
    base01 = "{{colors.surface_container.default.hex}}",
    base02 = "{{colors.surface_container_high.default.hex}}",
    base03 = "{{colors.outline.default.hex}}",
    base04 = "{{colors.on_surface_variant.default.hex}}",
    base05 = "{{colors.on_surface.default.hex}}",
    base06 = "{{palettes.neutral._90.hex}}",
    base07 = "{{palettes.neutral._95.hex}}",
    base08 = "{{colors.error.default.hex}}",
    base09 = "{{palettes.tertiary._60.hex}}",
    base0A = "{{palettes.secondary._80.hex}}",
    base0B = "{{palettes.primary._60.hex}}",
    base0C = "{{palettes.secondary._60.hex}}",
    base0D = "{{colors.primary.default.hex}}",
    base0E = "{{colors.tertiary.default.hex}}",
    base0F = "{{palettes.error._60.hex}}",
}
