return {
    base00 = "{{colors.surface.default.hex}}",
    base01 = "{{colors.surface_container.default.hex}}",
    base02 = "{{colors.surface_container_high.default.hex}}",
    base03 = "{{colors.outline.default.hex}}",
    base04 = "{{colors.on_surface_variant.default.hex}}",
    base05 = "{{colors.on_surface.default.hex}}",
    base06 = "{{colors.on_surface.default.hex | lighten: 5.0}}",
    base07 = "{{colors.on_surface.default.hex | lighten: 10.0}}",
    base08 = "{{colors.error.default.hex}}",
    base09 = "{{colors.tertiary.default.hex | darken: 10.0}}",
    base0A = "{{colors.secondary.default.hex | lighten: 5.0}}",
    base0B = "{{colors.primary.default.hex | darken: 10.0}}",
    base0C = "{{colors.secondary.default.hex}}",
    base0D = "{{colors.primary.default.hex}}",
    base0E = "{{colors.tertiary.default.hex}}",
    base0F = "{{colors.error.default.hex | darken: 15.0}}",
}
